server:
  port: 8080
  servlet:
    context-path: /api

spring:
  config:
    activate:
      on-profile: "dev"
  security:
    oauth2:
      resourceserver:
        jwt:
          public-key-location: classpath:public.key
  datasource:
    url: jdbc:mysql://localhost:3308/english_center_management?createDatabaseIfNotExist=true
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
  jackson:
    default-property-inclusion: always
  liquibase:
    user: root
    password:
logging:
  ignores-path:
    - "/api/assets/**"
security:
  private-key-location: classpath:private.key
  jwt-time: 1D
  permit-all:
    ALL:
      - /courses/search
      - /testings/search
    GET:
      - /courses
      - /questions/testing
    POST:
      - /testings/check
  cors:
    url: http://localhost:4200, http://localhost:4201

schedule:
  timetable:
    change-status:
      enabled: true # tự động thay đổi trạng thái của lịch dạy khi dạy đủ bài giảng
      cron: '* * * ? * *' # chạy mỗi giây
  bill:
    change-status:
      enabled: true # tự động thay đổi trạng thái của don hang
#      cron: '* * * ? * *' # chạy mỗi giây
      cron: '0 */5 * ? * *' # 5 phut cap nhat 1 lan
resource:
  provider: local
  local:
    path: 'D:\english-center-management-dev\english-center-management-be\asserts'
    host: http://localhost:${server.port}${server.servlet.context-path}/assets

payment:
  vnpay:
    pay-url: https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
    return-url: http://localhost:4201/xac-thuc-thanh-toan/vnpay
    tmn-code: YWQU6J2X
    secret-code: USVSYNNTO4Z9BKZEX1O8KHPI88FD64BE
    api-url: https://sandbox.vnpayment.vn/merchant_webapi/api
    version: 2.1.0
    timeout: 1M
    ccy: VND
    exp-order: 15M
    order-info-template: 'THANH TOAN %s'